### ISSUE TITLE
Copy logger class from dependency

### ISSUE THREAD

**Issue by Shelob9** [trustedlogin/client#105]
Related: #103

It's one file, put it in the plugin

**Comment by Shelob9** [comment]
@zackkatz I made PR #106 The thing I ran into is KLogger is dependent on psr/log, which is still a dependency.

Options:
1. Keep it. 
2. Copy/ simplify the few classes in psr/log it uses. 
3. The solution I don't like, that I used in vendor. https://github.com/trustedlogin/vendor/blob/develop/php/Traits/Logger.php

I'm done for day, will think about it. Let me know what happens if you think about it.

**Comment by zackkatz** [comment]
Right…psr/log is a pretty darn simply library. Since this would allow for us to remove all Composer dependencies, how horrible would it be to do \#2? It's only 8 files. KLogger is 1 file…

KLogger was updated once in the past 7.5 years last year for 8.1 support. psr/log hasn't been updated in two years.

I'm thinking \#2. What do you think?

**Comment by Shelob9** [comment]
I agree, let's do a two.

**Comment by Shelob9** [comment]
Was closed via  #106
